SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'AKB48グループ'), url: 'akb48-group')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'SKE48'), url: 'ske48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'NGT48'), url: 'ngt48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'STU48'), url: 'stu48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'AKB48'), url: 'akb48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'NMB48'), url: 'nmb48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'HKT48'), url: 'hkt48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ラストアイドルファミリー'), url: 'lastidol')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'LaLuce'), url: 'laluce')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Good Tears'), url: 'good-tears')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'シュークリームロケッツ'), url: 'shoecream-rockets')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Someday Somewhere'), url: 'someday-somewhere')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Love Cocchi'), url: 'love-cocchi')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'LDH(EXILE)'), url: 'ldh')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'E-girls'), url: 'e-girls')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '三代目 J Soul Brothers from EXILE TRIBE'), url: 'jsoulb')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'GENERATIONS from EXILE TRIBE'), url: 'generations-ldh')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Dream Ami'), url: 'ami-ldh')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'EXILE'), url: 'exile')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'THE RAMPAGE from EXILE TRIBE'), url: 'the-rampage')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ゲスの極み乙女。'), url: 'gesuotome')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ジェニーハイ'), url: 'genie-high')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'TWICE'), url: 'twicejapan')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'SEKAI NO OWARI'), url: 'sekainoowari')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'きゃりーぱみゅぱみゅ'), url: 'kyary')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Little Glee Monster'), url: 'littlegleemonster')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Perfume'), url: 'perfume')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '星野源'), url: 'hoshinogen')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '坂道シリーズ'), url: 'sakamichi')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '乃木坂46'), url: 'nogizaka46')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '欅坂46'), url: 'keyakizaka46')
# SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'けやき坂46'), url: '')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'UUUM'), url: 'uuum')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Fischer’s'), url: 'fischers')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'HIKAKIN & SEIKIN'), url: 'hikakin-seikin')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '米津玄師'), url: 'kenshiyonezu')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'back number'), url: 'backnumber')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ONE OK ROCK'), url: 'oneokrock')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Alexandros'), url: 'alexandros')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '宇多田ヒカル'), url: 'utadahikaru')

SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'マップ'), url: 'spot')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ジャンルからさがす'), url: 'categories')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ショッピング'), url: 'shopping')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '自然・公園'), url: 'nature-park')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '体験'), url: 'experience')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '動物園・水族館'), url: 'zoos-aquariums')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '雪・スノースポーツ'), url: 'snow')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'エンタメ・アミューズメント'), url: 'entertainment')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '観光施設・名所'), url: 'sightseeing-spot')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '神社・神宮・寺・寺院'), url: 'shrines-temples')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'プール'), url: 'swimming-pool')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '全般・感想'), url: 'impressions')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '温泉'), url: 'hot-springs')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ホテル・宿泊'), url: 'hotels')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'アスレチック・運動施設'), url: 'athletic-sports-facilities')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '祭り・イベント'), url: 'festivals')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '乗り物'), url: 'vehicles')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '伝統文化・日本文化'), url: 'traditional-culture')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '果物・野菜狩り'), url: 'fruits-vegetables')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'グルメ'), url: 'gourmet')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'アウトドア'), url: 'outdoor')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ウォーター＆マリンスポーツ'), url: 'marine-sports')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '海・ビーチ'), url: 'sea-beach')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'テーマパーク'), url: 'theme-park')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '場所からさがす'), url: 'places')
