SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'AKB48グループ'), url: 'akb48-group')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'SKE48'), url: 'ske48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'NGT48'), url: 'ngt48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'STU48'), url: 'stu48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'AKB48'), url: 'akb48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'NMB48'), url: 'nmb48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'HKT48'), url: 'hkt48')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ラストアイドルファミリー'), url: 'lastidol')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'LaLuce'), url: 'laluce')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Good Tears'), url: 'good-tears')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'シュークリームロケッツ'), url: 'shoecream-rockets')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Someday Somewhere'), url: 'someday-somewhere')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Love Cocchi'), url: 'love-cocchi')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'LDH(EXILE)'), url: 'ldh')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'E-girls'), url: 'e-girls')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '三代目 J Soul Brothers from EXILE TRIBE'), url: 'jsoulb')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'GENERATIONS from EXILE TRIBE'), url: 'generations-ldh')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Dream Ami'), url: 'ami-ldh')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'EXILE'), url: 'exile')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'THE RAMPAGE from EXILE TRIBE'), url: 'the-rampage')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ゲスの極み乙女。'), url: 'gesuotome')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ジェニーハイ'), url: 'genie-high')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'TWICE'), url: 'twicejapan')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'SEKAI NO OWARI'), url: 'sekainoowari')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'きゃりーぱみゅぱみゅ'), url: 'kyary')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Little Glee Monster'), url: 'littlegleemonster')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Perfume'), url: 'perfume')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '星野源'), url: 'hoshinogen')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '坂道シリーズ'), url: 'sakamichi')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '乃木坂46'), url: 'nogizaka46')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '欅坂46'), url: 'keyakizaka46')
# SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'けやき坂46'), url: '')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'UUUM'), url: 'uuum')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Fischer’s'), url: 'fischers')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'HIKAKIN & SEIKIN'), url: 'hikakin-seikin')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '米津玄師'), url: 'kenshiyonezu')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'back number'), url: 'backnumber')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'ONE OK ROCK'), url: 'oneokrock')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: 'Alexandros'), url: 'alexandros')
SpecialCategory.find_or_create_by!(category: Category.find_by(name: '宇多田ヒカル'), url: 'utadahikaru')
